### ISSUE TITLE
How to Get Data/Bit Rate for SX1280 in FLRC Mode

### ISSUE THREAD

**Issue by Yash-Varuni** [jgromes/RadioLib#831] opened 2023-09-18 07:33 UTC
### How to Get Data/Bit Rate in SX1280 in FLRC Mode
I have Used SX1268, where I can use radio.getDataRate() to get the Data Transmit Rate, but when I use it for SX1280 FLRC Modem compile show error message error: 'class SX1280' has no member named 'getDataRate'.

**Comment by jgromes** [comment] 2023-09-18 17:29
Closing as duplicate of discussion #830

**Closed by jgromes** 2023-09-18 17:29 UTC
