### ISSUE TITLE
Testing a RFM22 

### ISSUE THREAD

**Issue by lw2dtz** [jgromes/RadioLib#313] opened 2021-06-18 01:07 UTC
Hello,

I am testing a RFM22 module and an 8mhz arduino with the library in the following modes, in RTTY and Hellschreiber it has worked as indicated. In morse it transmits but instead of having a silence between brand and brand it remains like a carrier. 
Any idea what can it be? 

Regards.

Gustavo.

**Comment by jgromes** [comment] 2021-06-18 20:47
Seems the standby method got broken at some point - not sure why. Can you try with the fixed version?

**Comment by lw2dtz** [comment] 2021-06-18 21:11
Yes, I using Radiolib 4.41 version and IDE 1.8.9

**Comment by lw2dtz** [comment] 2021-06-19 00:41
Excellent, MORSE  is solved. 
Tried AX25 mode and there is not desviation, it gives error -102 and only a tone is heard.

**Comment by jgromes** [comment] 2021-06-19 11:40
I was not able to replicate this, please follow the issue template, post the sketch you're using and the debug mode output.

**Comment by lw2dtz** [comment] 2021-06-19 17:51
I leave you the sketch and the debug file.

[ax25_rfm22.txt](https://github.com/jgromes/RadioLib/files/6681121/ax25_rfm22.txt)
[debug_rfm22.txt](https://github.com/jgromes/RadioLib/files/6681123/debug_rfm22.txt)

**Comment by jgromes** [comment] 2021-06-19 18:15
Well then it's quite obvious:

```c++
int state = radio.begin(434.0, 1.2, 0.5);
```

You've set frequency deviation to 0.5 kHz - RFM22 (or any module from the Si443x/RFM2x family) can only go down to 0.625 kHz. Remove the 0.5 and it should work.

**Comment by lw2dtz** [comment] 2021-06-19 19:09
Yes, I change it, and it doesn't work. I only get this ... no FSK ,only a carrier

![image](https://user-images.githubusercontent.com/6095237/122653028-59be5c00-d118-11eb-9a65-1442212ca29e.png)

**Comment by jgromes** [comment] 2021-06-20 11:43
Seems like at some point, FSK modulation config was broken, fixed now and AX.25 checked with soundmodem.

**Comment by lw2dtz** [comment] 2021-06-20 14:47
Well, the AX25 is fixed and work!!

![radiolib_ax25_rfm22](https://user-images.githubusercontent.com/6095237/122678259-66948b80-d1bc-11eb-8ffb-d9def1765673.png)

But now the **RTTY and Hellschreiber** work bad,  it sounds as desynchronized. I'm sending you an RTTY recording.

https://user-images.githubusercontent.com/6095237/122678368-f4707680-d1bc-11eb-84ed-25f1cff2222c.mp4

**Comment by jgromes** [comment] 2021-06-20 15:05
Unforunately I was unable to reproduce this, on my end RTTY decodes fine in SDR Console and fldigi, and Hellschreiber decodes fine in fldigi.

Checking the file you sent, it looks like it's sending some really strange data. Please post the sketch you're using. Also, does this only happen on 8 MHz Arduino (I'm assuming Pro Mini)?

**Comment by lw2dtz** [comment] 2021-06-20 18:37
I posted the debug file and the skecth. I ony testing with a Pro Mini at 8 MHz.

[rtty_rfm22_ino.txt](https://github.com/jgromes/RadioLib/files/6682897/rtty_rfm22_ino.txt)

[debug_rfm22_rtty.txt](https://github.com/jgromes/RadioLib/files/6682883/debug_rfm22_rtty.txt)

**Comment by jgromes** [comment] 2021-06-20 18:44
Are you running them both with debug still enabled? If so, try disabling it. Debug mode is very slow, and in case of direct transmit modes like RTTY or Hellschreiber, it will have large impact on the timing.

**Comment by lw2dtz** [comment] 2021-06-20 21:05
You are right. Debugging mode slowed down the microcontroller. I took it out and the RTTY AND HELL started working fine.
Can SSTV mode work?  Tried but the soft goes into an infinite loop trying to initialize the RFM22.

[SSTV_RFM22.txt](https://github.com/jgromes/RadioLib/files/6683078/SSTV_RFM22.txt)

**Comment by jgromes** [comment] 2021-06-21 04:56
You might be able to do SSTV using Si443x/RFM2x, but probably only in AFSK mode (since Si443x FSK resolution is 156 Hz) and you will need something with more memory than Arduino Pro Mini.

**Closed by jgromes** 2021-06-21 04:56 UTC
Labels: bug
