### ISSUE TITLE
 [Bug,radiolib] wrong CMD_CalibrateImage sx1262 

### ISSUE THREAD

**Issue by mrx23dot** [jgromes/RadioLib#1141] opened 2024-06-28 12:06 UTC
I did an SPI measurement on heltec v3 board with meshtastic

it sends out CMD_CalibrateImage
`98 D8 DB `

based on datasheet it should be D7 DB

![image](https://github.com/jgromes/RadioLib/assets/4163396/b841fbb7-4aa6-4e29-b900-38abe450458b)

version:
https://github.com/meshtastic/firmware/issues/4193

**Comment by jgromes** [comment] 2024-06-28 15:10
This has been fixed in 5d741779a1badda90f20b7e6a320f958c6069ef9. The following information is missing and that prevents me to tell what exactly is going on here:

1. The version of RadioLib you are using
2. The wireless radio you are using
3. Meshtastic calbiration process

Follow the issue template, try to reproduce this in the minimum possible configuration (that is, without Meshtastic). Until it can be shown otherwise, I consider this a duplicate of an already resolved issue.

**Closed by jgromes** 2024-06-28 15:10 UTC
