### ISSUE TITLE
Feature request: AX.25 parser

### ISSUE THREAD

**Issue by ploeffler** [jgromes/RadioLib#1071] opened 2024-04-21 15:17 UTC
ax.25 frames can be created and sent, but not received

would be a big benefit to be able to create ax.25 "servers" to be connected to

**Comment by jgromes** [comment] 2024-04-21 15:24
Duplicate of #569 - see that issue for the current state and the roadblocks I have hit when attempting to implement this.

**Closed by jgromes** 2024-04-21 15:24 UTC
Labels: duplicate

**Comment by ploeffler** [comment] 2024-04-21 15:33
are we both aware of the fact, that ax.25 is not aprs?
--
Disclaimer: May be opened and read by the NSA, CIA, GCHQ, KGB, BND, and
whoever else it may NOT concern.


Am So., 21. Apr. 2024 um 17:25 Uhr schrieb Jan Gromeš <
***@***.***>:

**Comment by jgromes** [comment] 2024-04-21 15:43
And are we both aware that APRS uses AX.25 frames?

**Comment by ploeffler** [comment] 2024-04-21 16:06
Yes, we are!
--
Disclaimer: May be opened and read by the NSA, CIA, GCHQ, KGB, BND, and
whoever else it may NOT concern.


Am So., 21. Apr. 2024 um 17:44 Uhr schrieb Jan Gromeš <
***@***.***>:
