### ISSUE TITLE
LLCC68 Doesn't work

### ISSUE THREAD

**Issue by RJSDevel** [jgromes/RadioLib#331] opened 2021-07-20 06:36 UTC
I have connected LLCC68(Ra-01sc) module to Arduino UNO, but I have got different errors from SPI
1. Initializing ... failed, code -707 - if I set BUSY pin
2. [SX1262] Scanning channel for LoRa transmission ... failed, code -20 - if I remove BUSY in constuctor
I modify emaple from master for SX1262 to:
LLCC68 radio = new Module(10, 2, 3, 9);

The first 2 module wans't connected thought level-shift, and I thought that I had broken them, but I bought new modules and level-shift YF08E, but I had got the same errors.

I don't know what to do, I did all what I knew

The changes for example RadioLib SX126x Channel Activity Detection Example:
// SX1262 has the following connections:
// NSS pin:   10
// DIO1 pin:  2
// NRST pin:  3
// BUSY pin:  9
LLCC68 radio = new Module(10, 2, 3, 9);

![photo_2021-07-20_11-30-26](https://user-images.githubusercontent.com/12229274/126273145-59b0fd8f-1910-4713-aa0f-1c6f87537277.jpg)

**Additional info (please complete):**
 - MCU: Arduino Uno
 - LLCC68
 - Arduino IDE version 1.8.15
 - Library version From master

**Comment by RJSDevel** [comment] 2021-07-20 11:38
Add log to begin()

  int state = radio.begin();
  if (state == ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while (true);
  }

[SX1262] Initializing ... reset
16:37:21.606 -> 0
16:37:21.606 -> standby
16:37:21.606 -> 0
16:37:21.606 -> config
16:37:21.606 -> 0
16:37:21.606 -> setTCXO
16:37:21.653 -> 0
16:37:21.653 -> setSpreadingFactor
16:37:21.653 -> 0
16:37:21.653 -> setBandwidth
16:37:21.700 -> 0
16:37:21.700 -> setCodingRate
16:37:21.700 -> 0
16:37:21.747 -> setSyncWord
16:37:21.747 -> 0
16:37:21.747 -> setPreambleLength
16:37:21.747 -> 0
16:37:21.747 -> setCurrentLimit
16:37:21.747 -> 0
16:37:21.747 -> setDio2AsRfSwitch
16:37:21.795 -> 0
16:37:21.795 -> setRegulatorDCDC
16:37:21.842 -> 0
16:37:21.842 -> failed, code -707

**Comment by jgromes** [comment] 2021-07-20 15:34
Depending on the position on the logging prints, it could be that the error is returned from setRegulatorDCDC. If the module is not using a DC/DC converter, but an LDO, that would explain the error. Try to call begin() with useRegulatorLDO set to false (default is true).

**Comment by RJSDevel** [comment] 2021-07-20 15:36
16:37:21.795 -> setRegulatorDCDC
16:37:21.842 -> 0 <-- Result of setRegulatorDCDC

**Comment by RJSDevel** [comment] 2021-07-20 15:37
setRegulatorLDO

[SX1262] Initializing ... reset
20:37:21.889 -> 0
20:37:21.889 -> standby
20:37:21.889 -> 0
20:37:21.889 -> config
20:37:21.889 -> 0
20:37:21.889 -> setTCXO
20:37:21.936 -> 0
20:37:21.936 -> setSpreadingFactor
20:37:21.936 -> 0
20:37:21.936 -> setBandwidth
20:37:21.983 -> 0
20:37:21.983 -> setCodingRate
20:37:21.983 -> 0
20:37:21.983 -> setSyncWord
20:37:21.983 -> 0
20:37:21.983 -> setPreambleLength
20:37:22.030 -> 0
20:37:22.030 -> setCurrentLimit
20:37:22.030 -> 0
20:37:22.030 -> setDio2AsRfSwitch
20:37:22.076 -> 0
20:37:22.076 -> setRegulatorLDO
20:37:22.076 -> 0
20:37:22.076 -> failed, code -707

**Comment by RJSDevel** [comment] 2021-07-20 15:38
I don't know how it possible that the last method returned 0, but begin returned -707

**Comment by RJSDevel** [comment] 2021-07-20 15:41
I will try to use logical analiser analyzer to see what happend in SPI

**Comment by RJSDevel** [comment] 2021-07-20 15:44
Could you say to me if answers of those functions are 0, that means SPI is ok?

**Comment by jgromes** [comment] 2021-07-20 15:48
> I will try to use logical analyzer analyzer to see what happend in SPI

Alternatively you could enable the built-in debug mode. 

There's more than just a call to SX126x::begin(), there's also a call to SX1268::begin(), it might have failed somewhere in that.

**Comment by RJSDevel** [comment] 2021-07-20 15:50
I had changed SX1262 to LLCC68

**Comment by jgromes** [comment] 2021-07-20 15:53
>I had changed SX1262 to LLCC68

That doesn't matter, since LLCC68 class still inherits from SX1262. So when you call `radio.begin()` you're actually calling `SX1262::begin()`.

**Comment by RJSDevel** [comment] 2021-07-20 15:57
You are right! 
![image](https://user-images.githubusercontent.com/12229274/126356477-a16b5bd8-f675-4a87-8e66-c099ab575efa.png)
20:56:22.033 -> setRegulatorDCDC
20:56:22.033 -> 0
20:56:22.033 -> state
20:56:22.033 -> 0
20:56:22.033 -> failed, code -707

**Comment by RJSDevel** [comment] 2021-07-20 16:01
It overrided in SX1262 but not in LLCC68

**Comment by RJSDevel** [comment] 2021-07-20 16:02
I commented it 
![image](https://user-images.githubusercontent.com/12229274/126357260-411e5e85-05ec-4e09-8db2-149109e98f9b.png)

**Comment by RJSDevel** [comment] 2021-07-20 16:07
I have found what the deal!
![image](https://user-images.githubusercontent.com/12229274/126357900-b64867ec-266e-46ba-8401-2181f9685def.png)
setFrequency calibarations are wrong

**Comment by RJSDevel** [comment] 2021-07-20 16:10
![image](https://user-images.githubusercontent.com/12229274/126358350-97242d49-8a40-496f-9085-098495d20798.png)

**Comment by RJSDevel** [comment] 2021-07-20 16:23
But if send packets without interrupt appears timeout error?

**Comment by RJSDevel** [comment] 2021-07-21 10:15
The setFrequency wan't the main cause, because I'v changed not right condition

**Comment by jgromes** [comment] 2021-07-21 16:35
I don't understand why you felt the need to add `LLCC68::setFrequency()`, both `setFrequency()` and `begin()` are inherited from SX1262 class, since I wasn't able to find any difference between SX1262 and LLCC68 in that regard.

**Comment by RJSDevel** [comment] 2021-07-22 08:26
so do I, I have campare datasheets of those chips, I deleted what I changed, and clone repo again, and the chip doesn't work again, I don't know what happend, I will investigate this when I will have time

**Comment by RJSDevel** [comment] 2021-07-22 08:57
I found strange in datasheet:
![image](https://user-images.githubusercontent.com/12229274/126613778-99d67f54-f8d3-462d-a3a3-7f0e1d72b7eb.png)
![image](https://user-images.githubusercontent.com/12229274/126613869-214becea-42e6-46e7-9a66-0c926cb1f684.png)

**Comment by jgromes** [comment] 2021-07-22 18:45
That sort of inconsistency is fairly common in Semtech documentation, but it's not the root cause here, since we know that frequency configuration works flawlessly on all SX126x devices.

From your (fairly chaotic) posts, I can't determine whether there's an actual problem in the library at the moment, so I'm closing this issue. Feel free to open a new one once you have a reliable way to reproduce any unexpected behavior using unedited library. Also, please follow the issue template.

**Closed by jgromes** 2021-07-22 18:45 UTC

**Comment by RJSDevel** [comment] 2021-07-26 08:26
The same https://github.com/jgromes/RadioLib/issues/89

I will make merge request, we need to modify begin, remove tcxoVoltage from it, or override begin
tcxoVoltage have to be 0

**Comment by RJSDevel** [comment] 2021-07-26 08:29
if tcxoVoltage != 0, then calibration is failed, I connected analyser to spi and saw answer of LLCC68, it was 0xAA, this means that was calibration error

**Comment by RJSDevel** [comment] 2021-08-01 16:29
https://github.com/jgromes/RadioLib/pull/341
